### ISSUE TITLE
关于workflows运行失败的问题

### ISSUE THREAD

**Issue by itgoyo** [KeJunMao/bilibili-box#3]
![](https://cdn.jsdelivr.net/gh/itgoyo/PicGoRes@master/img/20210306143641.png)
你好，我使用项目的时候，不管是之前发fork基础上面修改还是我自己新建的项目，已经严格按照文档来执行了，还是出现这个错误
Gist是public的
GH_TOKEN生成时候所有钩我都打了，也尝试regenerate过一次
Bilibili UID 也确保无误了
但是Actions Workflows build 都是失败的，这个还有没有可能是什么别的原因呢？期待您的解答，谢谢

**Comment by itgoyo** [comment]
不好意思，现在可以了，刚刚把直播间的ID当成了自己的UID，后面用了个人资料里面的就解决了，最后还是要谢谢提供这么好的项目

**Comment by KeJunMao** [comment]
好耶，解决了就好
